CU-8669nuyaj/As-a-user-I-want-to-view-the-advertisements-on-the-home-page
mahmoud-birdsol/kjora pull request #79
Opened 2023-03-07 11:04 UTC by amlWalaed

CU-8669nuyaj/As-a-user-I-want-to-view-the-advertisements-on-the-home-page

2023-03-07 11:04 UTC, amlWalaed commented
Task linked: [CU-8669nuyaj As a user, I want to view the advertisements on the home page](https://app.clickup.com/t/8669nuyaj)

2023-03-08 09:28 UTC, mahmoud-birdsol requested changes

2023-03-08 09:28 UTC, mahmoud-birdsol commented on app/Jobs/CreateImpressionJob.php
> +            'user_id' => $this->request->user()->id,
Pass the user to the job constructor not the request

2023-03-09 13:33 UTC, mahmoud-birdsol approved these changes

2023-03-09 13:36 UTC, merged